# -----------------------------
# PostgreSQL configuration file
# -----------------------------
# Optimized for a 2GB RAM / 1 vCPU Droplet

# CONNECTIONS AND AUTHENTICATION
listen_addresses = '*'
max_connections = 100

# RESOURCE USAGE (Approx settings for 2GB RAM)
shared_buffers = 512MB
effective_cache_size = 1536MB
maintenance_work_mem = 128MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1 # SSD pricing
effective_io_concurrency = 200
work_mem = 2621kB
huge_pages = off
min_wal_size = 1GB
max_wal_size = 4GB

# WRITE-AHEAD LOG
wal_level = replica

# EXTENSIONS
shared_preload_libraries = 'pg_stat_statements'

# pg_stat_statements tuning
pg_stat_statements.max = 10000
pg_stat_statements.track = all

# LOGGING
log_timezone = 'UTC'
datestyle = 'iso, mdy'
timezone = 'UTC'

# LOCALE
lc_messages = 'en_US.utf8'
lc_monetary = 'en_US.utf8'
lc_numeric = 'en_US.utf8'
lc_time = 'en_US.utf8'
default_text_search_config = 'pg_catalog.english'
